language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  # api_key:
  #   secure: 3qa1wiaaEoV6qOTaBdRYApGqkISiK6XqwGTErXtt7UxQfP4nxAmhIlhUzeuyuqTiFWAZKJDCTIRbHDA7KGgaZWYvv3WVbq1Ymk7xKJU27/vTb/rnjXnsIFnYP6RfZhbRFZRH8UNVAWmzL+AWzPy9zCJj+lXotKEkMTubFZMtjczRngA7965j8mM5SgsplnjsWmCz6HvbS6nX2J6AXYm7y0RsUnfn7xeiyfEADJ4aog4SB0tCE6gWVLA06gC34UlCMHfZR0ChURij68A3i7ISs2eo/+Qs0Y+kQ4kgvkGkRkYnJPn4xugyT3Hi8rCIt2nkcGryxMXv6+7VNpokarzqjVHMFktW2wmGjANlz94BwHFGdkSPHWB/YlxE9E8z9wC7EsY+SDr41ajNIcToQzOSlF68ThEoEG+CnuDwd4TdHJlx0/KrH1uuCz95asCiPensBYT0l38t5BgVPra1MG9Yjj/7Gzlf/5/qxlEXTj6pLzK9p01F9svAfw9dkhje1MaefWR5LtRwkads9WEQdO7MbdYYQvB1Onidy8MkdQvPlNkgggwjiUPqihcWGsyS5W1BsrsjzkLPCRG3BrSOAUxZvwT/bZA3yEJaZZQBxB3GBsbcfyX/9o92EcbmXsG6pmyCV4JLtKcoWH4BLFhZXxGeUp4PtPagFa+Q42wAwQbRpgE=
  app: blog-app-test-integration
  on:
    repo: DavidDoes/blog-app-test-integration
